#!/bin/bash
if (( $EUID != 0 )); then
    echo "please run as root"
    exit
fi
sudo ""
moukey_location=$(moukey_location)
sudo moukey_register remove
sudo rm $moukey_location/moukey*
echo "Moukey removed from system"