#!/bin/bash
#curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/germanespinosa/moukey/master/scripts/moukey_install | sudo bash

if (( $EUID != 0 )); then
    echo "please run as root"
    exit
fi
sudo ""
echo "uninstalling moukey..."
moukey_location=$(moukey_location)
sudo moukey_register remove
sudo rm $moukey_location/moukey*
echo "Moukey removed from system"