#!/bin/bash
#curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/germanespinosa/moukey/master/scripts/install_core.sh | sudo bash

echo "installing prerequisites..."
sudo apt-get install cmake git libevdev-dev -y >/dev/null
tmp_dir=$(mktemp -d -t ci-XXXXXXXXXX)
cd $tmp_dir
echo "cloning repository..."
git clone -q https://github.com/germanespinosa/moukey.git
cd moukey
mkdir build
cd build
echo "creating make files..."
cmake .. >/dev/null
echo "building binaries..."
make > /dev/null
echo "installing..."
make install > /dev/null
sudo chmod +777 /usr/local/bin/moukey_register_server
sudo chmod +777 /usr/local/bin/moukey_register_client
echo "installation complete"