#!/bin/bash

if [ "$1" != "" ]; then
  echo "echo \"$1\"">> $1/moukey_location
  exit
fi

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do
  DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
done
DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"

echo "Moukey Server 0.1.2020 by German Espinosa "
echo "------------------------------------------"

if [ "$1" == "remove" ]; then
  cmd=""
else
  cmd="moukey_run &"
fi

input="/etc/rc.local"
if [ ! -f $input ]; then
    echo "creating $input"
    sudo echo '#!/bin/sh' > $input
    sudo echo '#' >> $input
    sudo echo '# rc.local' >> $input
    sudo echo '#' >> $input
    sudo echo '# This script is executed at the end of each multiuser runlevel.' >> $input
    sudo echo '# Make sure that the script will "exit 0" on success or any other' >> $input
    sudo echo '# value on error.' >> $input
    sudo echo '#' >> $input
    sudo echo '# In order to enable or disable this script just change the execution' >> $input
    sudo echo '# bits.' >> $input
    sudo echo '#' >> $input
    sudo echo '# By default this script does nothing.' >> $input
    sudo echo 'exit 0' >> $input
else
    echo "$input found. Adding automatic startup"
fi

output=$(mktemp)
added=0
while IFS= read -r line
do
  if [[ "$line" == "moukey_run"* ]]; then
    echo "#$line" >> $output
  else
    if [ "$line" == "exit 0" ]; then
      echo "$cmd" >> $output
      added=1
    fi
    echo "$line" >> $output
  fi
done < "$input"
if (( added == 1)); then
  sudo cp $output $input
fi
sudo chmod +x $input

echo "Moukey registered successfully. Reboot needed"
