#!/bin/bash

function show_params(){
  if [ "$1" == "-s" ]; then
    shift
    shift
    for arg in "$@"
    do
      echo "Serving $arg"
    done
  fi
}

echo "Moukey 0.1.2020 by German Espinosa "
echo "-----------------------------------"

file=$1

if [ "$1" == "" ]; then
  file="$(moukey_location)/moukey.cfg"
fi

if [ ! -f "$file" ]; then
  echo "configuration file not found. run moukey_server or moukey_client first"
  exit 1
fi

user=$(cat $file |head -n 1)
params=$(cat $file |tail -n 1)

eval "show_params $params"

eval "sudo -H -u $user moukey $params"
