#!/bin/bash
#curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/germanespinosa/moukey/master/scripts/moukey_install | sudo bash

if (( $EUID != 0 )); then
  echo "please run as root"
  exit
fi

moukey_location 2> /dev/null
if [ "$?" == "0" ]; then
  echo "a previous version of moukey was found. please run moukey_uninstall first"
  exit
fi

echo ""
echo "installing prerequisites..."
apt-get install cmake git libevdev-dev -y >/dev/null
tmp_dir=$(mktemp -d -t ci-XXXXXXXXXX)
cd $tmp_dir
echo "cloning repository..."
git clone -q https://github.com/germanespinosa/moukey.git
cd moukey
mkdir build
cd build
echo "creating make files..."
cmake .. -DCMAKE_BUILD_TYPE=Release >/dev/null
echo "building binaries..."
make > /dev/null
echo "installing..."
make install > /dev/null
echo "installation complete"