#!/bin/bash
if (( $EUID != 0 )); then
    echo "please run as root"
    exit
fi

echo "Moukey Client 0.1.2020 by German Espinosa "
echo "------------------------------------------"
read -p "server: " server
read -p "Select port[4749]: " port
if [ "$port" == "" ]; then
  port="4749"
fi
read -p "Select port[root]: " user
if [ "$user" == "" ]; then
  user="root"
fi
sudo echo "$user" > "$(moukey_location)/moukey.cfg"
sudo echo "-c $server $port" >> "$(moukey_location)/moukey.cfg"

echo "configuration file saved. run moukey_run to start moukey"
